[package]
name = "parser"
version.workspace = true
edition.workspace = true

[dependencies]
lexer = { path = "../lexer" }
parser_derive = { path = "../parser_derive" }
string_cache = "0.8.4"

[dev-dependencies]
pretty_assertions = "1.4.0"
